import { geologica, alegreyna } from "@/lib/fonts"
import Link from "next/link"
import { supabase } from "@/lib/supabase"

import type { Metadata } from "next"

export const revalidate = 300

export const metadata: Metadata = {
    title: "About — James",
}

const Tag = ({ label, like }: { label: string, like: boolean }) => (
    <span className={`${like ? "bg-green-400/30 text-green-800 dark:text-green-400" : "bg-red-400/30 text-red-800 dark:text-red-400"} font-semibold text-xs px-3 py-2 rounded-sm`}>
        {label}
    </span>
)

const page = async () => {

    const [{ data: likes }, { data: dislikes }] = await Promise.all([
        supabase.from("likes").select("id, value").order("created_at", { ascending: true }),
        supabase.from("dislikes").select("id, value").order("created_at", { ascending: true }),
    ])

    return (
        <div className="bg-[#f0f2f4] dark:bg-[#151718] min-h-screen px-10">
            <div className="max-w-xl w-full mx-auto pt-10 flex flex-col gap-8 pb-16">

                {/* About */}
                <section>
                    <h1 className={`${geologica.className} text-3xl font-bold dark:text-white mb-1`}>About me</h1>
                    <div className={`${alegreyna.className} text-2xl leading-relaxed text-gray-700 dark:text-gray-300 flex flex-col gap-3`}>
                        <p>I'm an all-around curious person who can't get enough of exploring new ideas and asking lots of questions.</p>
                        <p>In my free time, you can usually find me watching anime, coding, playing guitar, riding outside with the motorcycle or
                            simply spending time with those closest to me.</p>
                        <p>
                            I'm an advocate for working and learning in public. Its on my{" "}
                            <Link href="https://github.com/jamesdevydev" className="text-blue-500 hover:underline">Github</Link>!
                        </p>
                    </div>
                </section>

                {/* Like */}
                <section className="pt-4">
                    <h2 className={`${geologica.className} text-3xl font-bold dark:text-white mb-3`}>Like 😄</h2>
                    <div className="flex flex-wrap gap-2">
                        {likes?.map((tag) => <Tag key={tag.id} label={tag.value} like={true} />)}
                    </div>
                </section>

                {/* Dislike */}
                <section className="pt-4">
                    <h2 className={`${geologica.className} text-3xl font-bold dark:text-white mb-3`}>Dislike 😒</h2>
                    <div className="flex flex-wrap gap-2">
                        {dislikes?.map((tag) => <Tag key={tag.id} label={tag.value} like={false} />)}
                    </div>
                </section>

                {/* About this site */}
                <section className="pt-4">
                    <h2 className={`${geologica.className} text-3xl font-bold dark:text-white mb-2`}>About this site</h2>
                    <p className={`${alegreyna.className} text-2xl text-gray-700 dark:text-gray-400 leading-relaxed`}>
                        Everything you see here I have designed and built myself. The website is using{" "}
                        <Link href="#" className="text-blue-500">React</Link> and{" "}
                        <Link href="#" className="text-blue-500">Shadcn</Link> as the component library. The pages are generated by{" "}
                        <Link href="#" className="text-blue-500">NextJS</Link> and are hosted on{" "}
                        <Link href="#" className="text-blue-500">Vercel</Link>.
                    </p>
                </section>

            </div>
        </div>
    )
}

export default page